# Generated by Django 2.2.1 on 2019-05-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_auto_20190529_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='type',
            field=models.CharField(blank=True, choices=[('searchpartners', 'searchpartners'), ('ideas', 'ideas'), ('jobs', 'jobs')], max_length=100),
        ),
    ]
