# Generated by Django 2.2.1 on 2019-05-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_announcement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='type',
            field=models.CharField(blank=True, choices=[('Поиск партнера', 'searchpartners'), ('Идеи', 'ideas'), ('Работа', 'jobs')], max_length=100),
        ),
    ]
